import { BudgetCertificationDetailBudgetPartidaExpenseBaseEntity } from "./BudgetCertificationDetailBudgetPartidaExpenseBaseEntity"

export type BudgetCertificationDetailBudgetPartidaExpenseEntity =
  BudgetCertificationDetailBudgetPartidaExpenseBaseEntity
